---
version: '3.8'
services:
  app:
    user: "1000"
    build:
      context: .
      dockerfile: ./.devops/docker/Dockerfile
    volumes:
      - ./src:/app
    ports:
      - 5000:5000
    stdin_open: true
    tty: true

